name: Deploy Release

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      ref:
        required: true
        type: string
      release_id:
        required: true
        type: string

permissions:
  contents: read
  id-token: write

jobs:
  deploy-release:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    permissions:
      contents: read
      id-token: write
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
          fetch-depth: 1


      - name: Authenticate with Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.ENTRA_APPLICATION_ID }}
          tenant-id: ${{ secrets.ENTRA_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      