name: Build and Prepare Release

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
      
      - name: Install Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.126.1'
          extended: true
      
      - name: Lint Bicep Files
        run: |
          az bicep lint --file ./deploy/00.sub.resourceGroup.bicep
          az bicep lint --file ./deploy/01.group.staticWebSite.bicep
      
      - name: Publish the Site
        run: |
          hugo --minify
      
      - name: Package Public Site as Archive File
        run: |
          cd ./public
          zip -r ../blog-site.zip .
      
      - name: Attach Archive to Job
        uses: actions/upload-artifact@v4
        with:
          name: blog-site
          path: ./blog-site.zip

  prepare-release:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.event_name == 'push' }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Retrieve Archive
        uses: actions/download-artifact@v2
        with:
          name: blog-site
          path: .
      
      - name: Authenticate with Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.ENTRA_APPLICATION_ID }}
          tenant-id: ${{ secrets.ENTRA_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}