name: Build and Prepare Release

permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
      
      - name: Install Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.126.1'
          extended: true
      
      - name: Lint Bicep Files
        run: |
          az bicep lint --file ./deploy/00.sub.resourceGroup.bicep
          az bicep lint --file ./deploy/01.group.staticWebSite.bicep
      
      - name: Publish the Site
        run: |
          hugo --minify
      
      - name: Package Public Site as Archive File
        run: |
          cd ./public
          zip -r ../blog-site.zip .
      
      - name: Attach Archive to Job
        uses: actions/upload-artifact@v4
        with:
          name: blog-site
          path: ./blog-site.zip

  prepare-release:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.event_name == 'push' }}

    permissions:
      contents: write

    outputs:
      ref: ${{ github.env.BUILD_VERSION}}
      release_id: ${{ steps.create_release.outputs.id }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      
      - name: Set Build Version
        run: |
          echo "BUILD_VERSION=$(date --rfc-3339=date).${{ github.run_number }}.${{ github.run_attempt }}" >> $GITHUB_ENV

      - name: Retrieve Archive
        uses: actions/download-artifact@v4
        with:
          name: blog-site
          path: .
      
      - name: Create Tag
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/${{ env.BUILD_VERSION }}',
              sha: context.sha
            })
      
      - name: Create Release
        id: create_release
        uses: actions/github-script@v7
        with:
          script: |
            const response = await github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: '${{ env.BUILD_VERSION }}',
              name: '${{ env.BUILD_VERSION }}',
              draft: true,
              generate_release_notes: true
            });

            console.log(response);

            core.setOutput('upload_url', response.data.upload_url);
            core.setOutput('release_id', response.data.id);

      - name: Upload Release Assets
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.repos.uploadReleaseAsset({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: ${{ steps.create_release.outputs.release_id}},
              name: 'blog-site.zip',
              data: fs.readFileSync('./blog-site.zip')
            })

  trigger-release:
    needs: prepare-release
    uses: ./.github/workflows/deploy.yml
    with:
      environment: prod
      ref: ${{ needs.pre-release.outputs.ref }}
      release_id: ${{ needs.prepare-release.outputs.release_id }}
    secrets:
      inherit